//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nerdle_Lopputyö.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nerdle_Lopputyö.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10+10=20
        ///10+11=21
        ///10+12=22
        ///10+13=23
        ///10+14=24
        ///10+15=25
        ///10+16=26
        ///10+17=27
        ///10+18=28
        ///10+19=29
        ///10+20=30
        ///10+21=31
        ///10+22=32
        ///10+23=33
        ///10+24=34
        ///10+25=35
        ///10+26=36
        ///10+27=37
        ///10+28=38
        ///10+29=39
        ///10+30=40
        ///10+31=41
        ///10+32=42
        ///10+33=43
        ///10+34=44
        ///10+35=45
        ///10+36=46
        ///10+37=47
        ///10+38=48
        ///10+39=49
        ///10+40=50
        ///10+41=51
        ///10+42=52
        ///10+43=53
        ///10+44=54
        ///10+45=55
        ///10+46=56
        ///10+47=57
        ///10+48=58
        ///10+49=59
        ///10+50=60
        ///10+51=61
        ///10+52=62
        ///10+53=63
        ///10+54=64
        ///10+55=65
        ///10+56=66
        ///10+57=67
        ///10+58=68
        ///10+59=69
        ///10+60=70
        ///10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Calculations {
            get {
                return ResourceManager.GetString("Calculations", resourceCulture);
            }
        }
    }
}
